# Generated by Django 4.0.1 on 2022-02-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='user_Dob_day',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='user_Dob_month',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='user_Dob_year',
            field=models.CharField(default='0', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='0@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='user_gender',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
