# Generated by Django 4.0.1 on 2022-02-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_user_first_name_user_last_name_user_user_dob_day_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
