# Generated by Django 4.0.1 on 2022-02-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
